class Config:
    MYSQL_HOST = 'YOUR_HOST OR IP_ADDRESS'
    MYSQL_USER = 'YOUR_USER'
    MYSQL_PASSWORD = 'YOUR_PASSWORD'
    MYSQL_DB = 'YOUR_DBNAME'
    TWILIO_ACCOUNT_SID = 'YOUR_TWILIO_ACCOUNT_SID'
    TWILIO_AUTH_TOKEN = 'YOUR_TWILIO_AUTH_TOKEN'
    TWILIO_WHATSAPP_NUMBER = 'YOUR_TWILIO_WHATSAPP_NUMBER'
